# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-11 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvety', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvety',
            options={'verbose_name': 'цветы'},
        ),
        migrations.RenameField(
            model_name='cvety',
            old_name='metategi',
            new_name='meta',
        ),
    ]
