# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-11 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvety', '0002_auto_20170211_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvety',
            options={'verbose_name': 'цветок', 'verbose_name_plural': 'цветы'},
        ),
    ]
