# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-11 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvety', '0003_auto_20170211_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvety',
            options={'ordering': ['id', 'name', 'price'], 'verbose_name': 'цветок', 'verbose_name_plural': 'цветы'},
        ),
        migrations.AddField(
            model_name='cvety',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='cvety/photos', verbose_name='фото'),
        ),
    ]
