# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 05:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvety', '0004_auto_20170211_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvety',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='cvety',
            name='meta',
            field=ckeditor.fields.RichTextField(max_length=70, verbose_name='ключевые слова'),
        ),
        migrations.AlterField(
            model_name='cvety',
            name='name',
            field=ckeditor.fields.RichTextField(max_length=50, verbose_name='название'),
        ),
    ]
