# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvety', '0005_auto_20170216_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvety',
            name='meta',
            field=models.CharField(max_length=70, verbose_name='ключевые слова'),
        ),
        migrations.AlterField(
            model_name='cvety',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
    ]
