# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 14:00
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvety', '0008_auto_20170216_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvety',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='описание'),
        ),
    ]
