# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-11 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cvety', '0004_auto_20170211_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('phone', models.CharField(max_length=11, verbose_name='телефон')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('cvety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvety.Cvety', verbose_name='Цветы')),
            ],
        ),
    ]
