# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170216_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discript',
            field=models.CharField(default=34325435, max_length=150, verbose_name='имя'),
            preserve_default=False,
        ),
    ]
