# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_discript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cvety',
        ),
    ]
